[package]
name = "rustcrypto-ff"
version = "0.14.0-pre.1"
authors = [
    "Sean Bowe <ewillbefull@gmail.com>",
    "Jack Grigg <thestr4d@gmail.com>",
]
edition = "2021"
rust-version = "1.85"
description = "Library for building and interfacing with finite fields"
readme = "README.md"
documentation = "https://docs.rs/rustcrypto-ff/"
homepage = "https://github.com/RustCrypto/ff"
license = "MIT/Apache-2.0"
repository = "https://github.com/RustCrypto/ff"

[dependencies]
bitvec = { version = "1", default-features = false, optional = true }
byteorder = { version = "1", default-features = false, optional = true }
ff_derive = { version = "=0.14.0-pre.0", package = "rustcrypto-ff_derive", path = "ff_derive", optional = true }
rand_core = { version = "0.10.0-rc-6", default-features = false }
subtle = { version = "2.2.1", default-features = false, features = ["i128"] }

[dev-dependencies]
blake2b_simd = "1"
rand = "0.10.0-rc.1"

[features]
default = ["bits", "std"]
alloc = []
bits = ["bitvec", "ff_derive?/bits"]
derive = ["byteorder", "ff_derive"]
std = ["alloc"]

[[test]]
name = "derive"
required-features = ["derive"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[patch.crates-io.rand]
git = "https://github.com/rust-random/rand"
branch = "rand_core/v0.10.0-rc-6"
